### ISSUE TITLE
Typescript mismatch with toBeTrue/toBeFalse as of @types/jasmine 3.5.0

### ISSUE THREAD

**Issue by tomyam1** [JamieMason/Jasmine-Matchers#124]
## Description

When using recent jasmine-expect 4.0.3 with @types/jasmine 3.5.0 we get the following errors:

```
TypeScript error: node_modules/jasmine-expect/dist/toBeFalse.d.ts(5,13): Error TS2717: Subsequent property declarations must have the same type.  Property 'toBeFalse' must be of type '() => boolean', but here has type 'ToBeFalse'.
TypeScript error: node_modules/jasmine-expect/dist/toBeTrue.d.ts(5,13): Error TS2717: Subsequent property declarations must have the same type.  Property 'toBeTrue' must be of type '() => boolean', but here has type 'ToBeTrue'.
```

## Suggested Solution

This seems to be due this commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c0e76f846ea10b34f3a22a49d33cfa879ea8c0ba

Using @types/jasmine 3.4.6 for now

## Help Needed

Not sure who got it right: jasmine-expect or @types/jasmine

**Comment by komyg** [comment]
Hi,

I ran into the same problem with Jasmine in an Angular project. I managed to solve it by removing the `jasmine-expect` entry that I had in my `tsconfig.spec.json` file:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "types": [
      "jasmine",
      "node",
      "jasmine-expect" # Removed this Line.
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by Necroskillz** [comment]
jasmine 3.5 now has it's own `toBeTrue` and `toBeFalse` matchers, so they could just be removed from this library.

**Comment by RobARichardson** [comment]
Had to revert back to Jasmine Core 3.4.0 to get around this issue for now.

**Comment by devoto13** [comment]
@JamieMason Would you be willing to accept a PR to remove `expectationFailOutput?: any` parameter from `.toBeTrue()` and `.toBeFalse()` matchers to prevent conflict with built-in matchers with the same name available as of [Jasmine 3.5.0](https://github.com/jasmine/jasmine/blob/master/release_notes/3.5.0.md)? This will require a major release as it is a breaking change.

Not suggesting complete removal of the matchers as Jest does not have them and also because it will affect more people then removal of the optional parameter.

For Jasmine `expectationFailOutput` works because of an implementation detail and is [not a supported usage](https://github.com/jasmine/jasmine/issues/641#issuecomment-54736801). That's why Jasmine 3.3.0 introduced [`.withContext()`](https://jasmine.github.io/api/edge/matchers.html#withContext) as supported way to add more information to the assertion.

Not sure how does this influence Jest users for the library though.

PS I will also try to deprecated `expectationFailOutput` parameters in `@types/jasmine` package in the coming weeks. If that goes through it should be a good idea to deprecate this parameter in all `jasmine-expect` matchers, so people would migrate from the unsupported usage.

**Comment by ShaneYu** [comment]
Is there any progress on this @JamieMason? The read me details that this library supports **all** versions of jest and Jasmine; but currently doesn't work with the last few releases of Jasmine.
> A huge library of test matchers for a range of common use-cases, compatible with all versions of Jasmine and Jest.

**Comment by hoeni** [comment]
Did anyone here find a better workaround than pinning down Jasmine and its types to 3.4 until this gets fixed for good?
