### ISSUE TITLE
Protractor configuration?

### ISSUE THREAD

**Issue by hkong** [JamieMason/Jasmine-Matchers#60]
Sorry for the n00b question, I'm fairly new to Protractor and Jasmine.  I'm using Protractor to do e2e testing and would like to use these matchers.  However, I'm not able to get protractor to recognize these matchers.  I've followed directions for NodeJS in the README, used `npm` to install the module, and can see the module in my project's `node_modules` directoyr.  I've applied the path to `"helpers"` in the jasmine.json file in protractor's spec/support subdirectory, but I still get 

`Failed: expect(...).toBeArray is not a function`

Any suggestions would be greatly appreciated.

**Comment by JamieMason** [comment]
I've not used Protractor before @hkong but if I get some time I will try to look at how to set it up. If you figure this out before me please share so I can add to the docs. Thanks.

**Comment by paulpreibisch** [comment]
Hey hKong and JamieMason,

I also am using Protractor for Angular.js e2e testing!  To get jasmineMatchers working, just add the following at the top of your mytest.spec.js

`require('./../../jasmine-matchers.js');
`
Note in the above, I place ./../../  that is because I have placed my jasmine-matchers.js file at the root of my tests folder:

```
tests
|
|-->e2e
     |-->login
         |-->mytests.spec.js
|
jasmine-matchers.js
```

Hope this helps

**Comment by bvasilchik** [comment]
I was able to get it working by using 

```
onPrepare: function() {
    require('jasmine-expect');
}
```

**Comment by JamieMason** [comment]
Thanks 😎👍

**Comment by JamieMason** [comment]
Will pick this up in #72 by adding an example project, thanks.
